name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Supabase Backend
  supabase_flutter: ^2.0.0
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI
  google_fonts: ^6.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  
  assets:
    - lib/core/assets/person_sitting.png
    - lib/core/assets/stop_watch.png
    - lib/core/assets/calender.png
    - lib/core/assets/pie_chart.png
    - lib/core/assets/smartnotification.png
    - lib/core/assets/flower.png
    - lib/core/assets/coffee.png
    - lib/core/assets/profile_image.png
